# Generated by Django 5.2.15 on 2026-06-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
